python3 main.py \
-c config.yaml \
-d /Users/banboooo044/Documents/speaker_class/data \
-train_set train_128 \
-train_index_file train_samples_128.json \
--use_eval_set \
-eval_set in_test \
-eval_index_file in_test_samples_128.json \
-logdir /Users/banboooo044/Documents/vc/log \
-store_model_path /Users/banboooo044/Documents/vc/model \
-tag exp1 \
-iters 500000 \
-summary_step 1000